name = "curated-store-bot"
main = "index.js"
compatibility_date = "2024-09-01"

account_id = "c37efe52fd944c09bbfe371b4ae944f1"

# Bind Cloudflare KV Namespace for products
[[kv_namespaces]]
binding = "STORE_KV"
id = "309e95eb480849caa8d912a8ec2a5c5f"

# Environment Variables / Secrets
# Run:
#   npx wrangler secret put TELEGRAM_BOT_TOKEN
#   npx wrangler secret put ALLOWED_USER_IDS
[vars]
AMAZON_TAG = "dhrav-21"
