import json

# 122 Curated Screen-Free Activities across 6 Categories

ACTIVITIES = [
  # -------------------------------------------------------------
  # 1. 🚀 HIGH ENERGY & ACTION (22 Activities)
  # -------------------------------------------------------------
  {
    "id": "floor_lava",
    "title": "Living Room 'Floor is Lava' Obstacle Island",
    "category": "High Energy & Action",
    "icon": "🌋",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Cushions, pillows, small towels, or cardboard squares.",
    "play": "Scatter cushions across the living room carpet. Move from the sofa to the kitchen doorway without your feet touching the bare floor!",
    "bonus": "Time yourself with a stopwatch or carry an 'ancient treasure' (stuffed toy) without dropping it.",
    "amazon": "indoor obstacle course for kids"
  },
  {
    "id": "laser_maze",
    "title": "Mission Impossible Hallway Laser Maze",
    "category": "High Energy & Action",
    "icon": "🕵️",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Masking tape or red yarn/wool, hallway walls.",
    "play": "Tape criss-crossing strands of yarn between opposite hallway walls at different heights. Crawl, limbo, and step through without touching a single laser strand!",
    "bonus": "Hang small bell ornaments from 2 strands—if a bell jingles, the alarm is triggered!",
    "amazon": "masking tape for kids crafts"
  },
  {
    "id": "balloon_volleyball",
    "title": "Don't Let the Balloon Touch the Ground!",
    "category": "High Energy & Action",
    "icon": "🎈",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "1 inflated balloon (or beach ball), a piece of string or two chairs for a net.",
    "play": "Keep the balloon airborne using only gentle taps. Count consecutive hits or play a seated living room volleyball match across the sofa.",
    "bonus": "Level 2: Play using only elbows, knees, or head taps—no hands allowed!",
    "amazon": "biodegradable party balloons kids"
  },
  {
    "id": "sock_cricket",
    "title": "Hallway Sock-Toss Cricket & Target Bowling",
    "category": "High Energy & Action",
    "icon": "🏏",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Rolled-up pairs of clean socks, plastic water bottles or cardboard boxes as wickets.",
    "play": "Set up 3 plastic bottles as stumps at the end of the hallway. Stand 10 paces away and practice spin and pace bowling to knock down the targets.",
    "bonus": "Assign point values to different bottles: center stump = 100 pts, edge = 50 pts.",
    "amazon": "indoor cricket kit foam ball"
  },
  {
    "id": "freeze_dance",
    "title": "DJ Freeze Dance & Animal Statues",
    "category": "High Energy & Action",
    "icon": "💃",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "Music player / phone with family playlist.",
    "play": "One person is the DJ who plays upbeat music while everyone dances wildly. When the DJ pauses the track, everyone must freeze instantly in place!",
    "bonus": "Animal twist: The DJ calls out an animal before starting (e.g. 'Flamingo!' or 'T-Rex!') and you must freeze in that animal's pose.",
    "amazon": "bluetooth party speaker for kids"
  },
  {
    "id": "indoor_hopscotch",
    "title": "Painter's Tape Indoor Hopscotch & Agility Ladder",
    "category": "High Energy & Action",
    "icon": "🪜",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Low-tack painter's masking tape, hallway or tile floor, rolled sock marker.",
    "play": "Tape out an 8-square hopscotch grid or 6-rung footwork ladder on the floor. Hop, jump, and test agility routines safely indoors.",
    "bonus": "Practice backward hopping or two-feet out, one-foot in football drill patterns.",
    "amazon": "painters tape blue masking"
  },
  {
    "id": "pillow_fort_siege",
    "title": "The Royal Bed-Sheet & Pillow Castle Citadel",
    "category": "High Energy & Action",
    "icon": "🏰",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Dining chairs, bedsheets, blankets, clothespins/heavy books to anchor.",
    "play": "Drape bedsheets over chairs and sofa backrests to engineer a multi-room secret fortress with an escape crawl tunnel and lookout window.",
    "bonus": "Bring inside a flashlight and storybooks to convert it into your private midnight reading den.",
    "amazon": "kids fort building kit"
  },
  {
    "id": "sock_skating",
    "title": "Hardwood Floor Sock Figure Skating",
    "category": "High Energy & Action",
    "icon": "⛸️",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Fluffy winter socks, clear tiled or hardwood hallway floor.",
    "play": "Slip on thick socks on a smooth floor and perform safe glide turns, spins, and slow-motion figure skating choreography to classical music.",
    "bonus": "Set up 2 plastic cups as slalom gates to glide between.",
    "amazon": "cozy grip socks kids"
  },
  {
    "id": "crab_walk_soccer",
    "title": "Reverse Crab-Walk Living Room Soccer",
    "category": "High Energy & Action",
    "icon": "🦀",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Family",
    "needs": "A soft foam ball or balloon, two chair legs as goalposts.",
    "play": "Both players must support themselves on hands and feet belly-up in crab position. Kick and block the soft ball into each other's goals!",
    "bonus": "Great core and shoulder workout disguised as belly-laugh chaos.",
    "amazon": "soft indoor soccer ball foam"
  },
  {
    "id": "scavenger_hunt",
    "title": "Color Rainbow Scavenger Hunt Sprint",
    "category": "High Energy & Action",
    "icon": "🌈",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Basket or tote bag, timer.",
    "play": "Set a 5-minute timer. Sprint around the house to collect exactly 1 item for every color of the rainbow: Red, Orange, Yellow, Green, Blue, Purple!",
    "bonus": "Level 2: Letter hunt! Find an item starting with every letter of your name.",
    "amazon": "scavenger hunt card game kids"
  },
  {
    "id": "paper_plate_tennis",
    "title": "Paper-Plate & Popsicle-Stick Balloon Tennis",
    "category": "High Energy & Action",
    "icon": "🎾",
    "prep": "3 min",
    "mess": "Low Mess",
    "energy": "High Energy",
    "mode": "Sibling or Duo",
    "needs": "2 paper plates, 2 wooden rulers or popsicle sticks, tape, 1 balloon.",
    "play": "Tape rulers to the back of paper plates to create tennis racquets. Volley the balloon back and forth across the dining table.",
    "bonus": "First to reach 21 points without letting the balloon touch the tabletop wins the Wimbledon cup!",
    "amazon": "paper plates bulk craft"
  },
  {
    "id": "fitness_dice",
    "title": "DIY Superhero Workout Challenge Roll",
    "category": "High Energy & Action",
    "icon": "🎲",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Family",
    "needs": "1 playing die (or coin), open carpet.",
    "play": "Roll the die: 1 = 10 Jumping Jacks, 2 = 10 Frog Leaps, 3 = 15-sec Superman hold, 4 = 10 High Knees, 5 = 10 Bear Crawl steps, 6 = Wild Dance!",
    "bonus": "Can you complete 5 rounds without taking a water break?",
    "amazon": "fitness dice for kids"
  },
  {
    "id": "hallway_bowling",
    "title": "Recycled Plastic Bottle Bowling Alley",
    "category": "High Energy & Action",
    "icon": "🎳",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "6 or 10 empty plastic bottles or cups, tennis ball or rolled socks.",
    "play": "Set bottles up in a triangle (4-3-2-1). Step back 15 feet down the hallway and roll the ball to score strikes and spares over 10 frames.",
    "bonus": "Fill bottles with 1 inch of water for weighted, professional pin-strike physics!",
    "amazon": "kids foam bowling set"
  },
  {
    "id": "shadow_tag",
    "title": "Outdoor Balcony / Patio Shadow Tag",
    "category": "High Energy & Action",
    "icon": "👥",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Family",
    "needs": "Sunny outdoor yard, terrace, or balcony.",
    "play": "No touching people allowed—you can only tag someone by stepping on their cast shadow on the ground! Dodge and weave to hide your shadow.",
    "bonus": "Try playing at 4 PM when shadows stretch extra-long!",
    "amazon": "outdoor play games for kids"
  },
  {
    "id": "carpet_curling",
    "title": "Kitchen Tile Slide & Glide Curling",
    "category": "High Energy & Action",
    "icon": "🥌",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Duo",
    "needs": "Jar lids, tape, target bullseye drawn on paper.",
    "play": "Tape a bullseye circle on the kitchen floor. Slide jar lids from 10 feet away trying to land closest to the center button without overshooting.",
    "bonus": "Knock your opponent's sliding lid out of the circle just like Olympic curling!",
    "amazon": "tabletop curling game"
  },
  {
    "id": "stuffed_animal_rescue",
    "title": "The Great Stuffed Animal Rescue Expedition",
    "category": "High Energy & Action",
    "icon": "🧸",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "5-10 stuffed toys, clothes pegs or laundry basket.",
    "play": "Parent or sibling 'traps' stuffed animals in tricky spots around the room (on high shelves, behind doors, under chairs). Rescue all 10 before the timer expires!",
    "bonus": "Transport each animal back to safety on a tray balanced on your head.",
    "amazon": "stopwatch timer for kids"
  },
  {
    "id": "wheelbarrow_race",
    "title": "Living Room Wheelbarrow Walk & Bear Relay",
    "category": "High Energy & Action",
    "icon": "🚜",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling with Parent",
    "needs": "Carpeted room.",
    "play": "Parent or older sibling holds child's ankles while child walks forward on their hands across the living room carpet to a goal post and back.",
    "bonus": "Switch to bear crawls: move across the room with hands and feet flat on the floor.",
    "amazon": "gymnastics mat folding kids"
  },
  {
    "id": "pillowcase_sack_race",
    "title": "Hallway Pillowcase Hop & Sack Race",
    "category": "High Energy & Action",
    "icon": "🦘",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Duo",
    "needs": "2 old pillowcases, carpeted hallway.",
    "play": "Step both feet inside a sturdy pillowcase, hold the fabric at your hips, and hop from one end of the carpeted hallway to the other.",
    "bonus": "Best of 3 races crowned as the Champion Kangaroo of the household.",
    "amazon": "sack race bags kids"
  },
  {
    "id": "balloon_waddle",
    "title": "Penguin Balloon Waddle Relay",
    "category": "High Energy & Action",
    "icon": "🐧",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "1 inflated balloon.",
    "play": "Place the balloon between your knees and waddle like an Antarctic penguin from room to room without letting the balloon drop or pop!",
    "bonus": "Collect plastic spoons along the way and place them in a bowl at the finish line.",
    "amazon": "party game balloons"
  },
  {
    "id": "laundry_basketball",
    "title": "Championship Laundry Basket Three-Point Shootout",
    "category": "High Energy & Action",
    "icon": "🏀",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Laundry basket, rolled-up socks or soft ball, tape marks for 1-pt, 2-pt, and 3-pt line.",
    "play": "Place the laundry hamper against a wall. Tape shooting lines on the floor. Take 10 shots from each distance and tally your NBA score!",
    "bonus": "Perform a celebration buzzer-beater victory dance when you sink a 3-pointer.",
    "amazon": "indoor mini basketball hoop"
  },
  {
    "id": "simon_says",
    "title": "Master Simon Says Extreme Ninja Edition",
    "category": "High Energy & Action",
    "icon": "🥋",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "3 or more players.",
    "play": "Leader calls out quick commands: 'Simon says touch your left ear with your right foot!', 'Simon says spin 3 times!'. If they don't say 'Simon says', don't move!",
    "bonus": "Fast-paced round: Increase speed every 10 seconds until only 1 ninja remains standing.",
    "amazon": "simon electronic memory game"
  },
  {
    "id": "tape_balance_beam",
    "title": "Olympic Tightrope Painter's Tape Balance Beam",
    "category": "High Energy & Action",
    "icon": "🎪",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Painter's tape stuck in straight and zigzag lines on carpet/floor.",
    "play": "Walk heel-to-toe across the tape tightrope suspended over an imaginary 10,000-foot canyon. No stepping off the line!",
    "bonus": "Try it backward, on tiptoes, or carrying a book flat on your head like a runway model.",
    "amazon": "balance stepping stones kids"
  },

  # -------------------------------------------------------------
  # 2. 🎨 CREATIVE & CRAFT STUDIO (22 Activities)
  # -------------------------------------------------------------
  {
    "id": "cardboard_spaceship",
    "title": "Epic Cardboard Delivery-Box Spaceship / Cockpit",
    "category": "Creative & Craft Studio",
    "icon": "🚀",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "1 large cardboard shipping box, markers, plastic bottle caps, paper plates.",
    "play": "Transform an Amazon delivery box into an interplanetary rocket. Draw altitude dials, thruster switches, radar screens, and paper plate steering wheels.",
    "bonus": "Add aluminum foil antenna boosters to communicate with Houston Mission Control.",
    "amazon": "crayola washable markers bulk"
  },
  {
    "id": "comic_book_creator",
    "title": "Create Your Own 4-Page Superhero Comic Book",
    "category": "Creative & Craft Studio",
    "icon": "💥",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "2 blank sheets of paper folded into a 4-page booklet, pencil, colored pens.",
    "play": "Draw speech bubbles, action panels, and invent a brand-new superhero (e.g. 'Captain Samosa' or 'Laser Cat'). Create a dramatic cliffhanger ending!",
    "bonus": "Write an 'Issue #1 Limited Edition' cover price and author signature on the front.",
    "amazon": "blank comic book for kids"
  },
  {
    "id": "secret_cipher_book",
    "title": "Ancient Egyptian Secret Code & Cipher Journal",
    "category": "Creative & Craft Studio",
    "icon": "📜",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Notebook, pen, Caesar cipher key or symbol substitution grid.",
    "play": "Invent a code where every letter of the alphabet is replaced by a glyph, number, or rune (A = ⭐, B = 🌙). Write a secret letter to a sibling or parent to decode.",
    "bonus": "Dip paper in watered-down black tea and dry it on a towel for antique parchment texture!",
    "amazon": "spy kit for kids secret agent"
  },
  {
    "id": "salt_dough_fossils",
    "title": "Homemade Dinosaur Bone Salt Dough Fossils",
    "category": "Creative & Craft Studio",
    "icon": "🦖",
    "prep": "10 min",
    "mess": "Craft Fun",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "1 cup flour, 1/2 cup salt, 1/2 cup water, toy plastic dinosaurs or leaves.",
    "play": "Mix flour, salt, and water to knead pliable dough. Flatten into disks and press toy dinosaur footprints or shells firmly into the surface to cast prehistoric fossils.",
    "bonus": "Air dry for 24 hours (or bake low at 120°C for 2 hours) and paint them with brown/gold accents.",
    "amazon": "dinosaur figures toy set"
  },
  {
    "id": "origami_zoo",
    "title": "Origami Jumping Frogs & Menagerie Zoo",
    "category": "Creative & Craft Studio",
    "icon": "🐸",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Square origami or colored paper sheets.",
    "play": "Fold classic jumping origami frogs, cranes, and puppy dogs. Press down on the frog's spring back to race them across the dining table!",
    "bonus": "Draw tiny googly eyes and spot patterns on your amphibian racer.",
    "amazon": "origami paper kit for kids"
  },
  {
    "id": "shadow_puppet_theater",
    "title": "Flashlight Shadow Puppet Bedtime Theater",
    "category": "Creative & Craft Studio",
    "icon": "🎭",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Family Challenge",
    "needs": "Flashlight or phone torch, dark room, cardboard cutouts taped to wooden skewers.",
    "play": "Shine a flashlight against a white bedroom wall. Cast hand shadows (rabbit, bird, wolf) or silhouette cardboard characters to perform a 5-minute bedtime play.",
    "bonus": "Use a white bedsheet hung in a doorway as a backlit cinema screen!",
    "amazon": "shadow puppet theater set"
  },
  {
    "id": "leaf_rubbing_botanical",
    "title": "Balcony Leaf & Tree Bark Botanical Wax Rubbings",
    "category": "Creative & Craft Studio",
    "icon": "🍃",
    "prep": "3 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Fallen leaves with prominent veins, white paper, wax crayons with paper wrappers peeled.",
    "play": "Place leaves vein-side up under a sheet of paper. Rub the broad side of a crayon flat over the paper to magically reveal intricate leaf veins and skeletons.",
    "bonus": "Label each leaf like an 18th-century naturalist with common and imaginary scientific names.",
    "amazon": "crayola crayons 64 box"
  },
  {
    "id": "recycled_robot",
    "title": "Recycled Tin-Can & Cereal Box Robot 'Byte'",
    "category": "Creative & Craft Studio",
    "icon": "🤖",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Empty cereal box, toilet paper rolls, aluminum foil, glue/tape, bottle caps.",
    "play": "Wrap boxes and tubes in shiny foil. Glue on bottle cap eyes, pasta gear teeth, and pipe cleaner antennas to engineer your own loyal household android.",
    "bonus": "Write an 'Owner Operating Manual' listing your robot's 3 secret superpowers and recharge recipe.",
    "amazon": "aluminum foil heavy duty"
  },
  {
    "id": "diy_stamp_pad",
    "title": "Potato & Eraser Printmaking Stamp Studio",
    "category": "Creative & Craft Studio",
    "icon": "🥔",
    "prep": "5 min",
    "mess": "Craft Fun",
    "energy": "Creative Arts",
    "mode": "Solo with Parent Help",
    "needs": "Raw potato half or school rubber eraser, dull butter knife, watercolor or paint.",
    "play": "Parent helps carve simple geometric shapes (star, heart, lightning bolt, triangle) into a potato cut-surface. Dip in paint and stamp custom wrapping paper patterns!",
    "bonus": "Stamp customized handmade birthday cards for upcoming family milestones.",
    "amazon": "washable finger paints kids"
  },
  {
    "id": "cozy_macaroni_jewelry",
    "title": "Golden Dyed Macaroni Royal Necklaces & Crowns",
    "category": "Creative & Craft Studio",
    "icon": "👑",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Penne or macaroni pasta, yarn/string, food coloring or paint.",
    "play": "Paint pasta tubes in radiant gold and royal jewel tones. Thread them onto yarn to craft regal necklaces, bracelets, and pharaoh crowns.",
    "bonus": "Add button beads or paper sequins between pasta tubes for high-fashion royal couture.",
    "amazon": "yarn for knitting crafts"
  },
  {
    "id": "marble_maze_box",
    "title": "Shoebox Lid Marble Labyrinth Maze",
    "category": "Creative & Craft Studio",
    "icon": "🌀",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Shoebox lid or shallow box, plastic drinking straws or popsicle sticks, glue, 1 marble.",
    "play": "Glue straws inside a shoebox lid to construct maze corridors with dead ends and pitfalls. Tilt the lid with both hands to navigate the marble from START to FINISH.",
    "bonus": "Cut out 2 small 'black hole' traps where the marble drops through if you're not steady!",
    "amazon": "glass marbles for kids"
  },
  {
    "id": "fingerprint_doodles",
    "title": "Thumbprint Creatures & Monster Comic Strip",
    "category": "Creative & Craft Studio",
    "icon": "🐾",
    "prep": "2 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Washable ink pad or water-moistened watercolor paint, white paper, fine black pen.",
    "play": "Press your inked thumb and fingertips onto paper. Once dry, draw tiny legs, antennae, googly eyes, and wings with a black pen to bring cute creatures to life!",
    "bonus": "Create a whole thumbprint zoo: lions, hedgehogs, giraffes, bees, and aliens.",
    "amazon": "washable craft ink stamp pads"
  },
  {
    "id": "stained_glass_tissue",
    "title": "Faux Cathedral Stained Glass Window Art",
    "category": "Creative & Craft Studio",
    "icon": "🪟",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Black construction paper, colorful tissue paper squares, clear tape or contact paper.",
    "play": "Cut silhouette shapes out of black paper (butterflies, mandalas, geometric stars). Tape bright translucent tissue paper behind cutouts and tape to a sunlit window!",
    "bonus": "Watch morning sunlight cast vibrant jewel-toned beams across the living room carpet.",
    "amazon": "tissue paper squares craft"
  },
  {
    "id": "rock_pet_family",
    "title": "Garden Pebble & Rock Pet Adoption Agency",
    "category": "Creative & Craft Studio",
    "icon": "🪨",
    "prep": "5 min",
    "mess": "Craft Fun",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Smooth garden pebbles or river stones, acrylic paints, fine brush or markers.",
    "play": "Wash smooth stones from the garden. Paint them into ladybugs, sleeping cats, galaxy rocks, or quirky pet monsters with googly eyes.",
    "bonus": "Make an official 'Certificate of Adoption' with pet name, favorite food, and birthday.",
    "amazon": "rock painting kit for kids"
  },
  {
    "id": "diy_story_dice",
    "title": "Handmade Wooden Cube Storyteller Dice",
    "category": "Creative & Craft Studio",
    "icon": "🎲",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Family",
    "needs": "Blank wooden craft cubes (or square paper fold blocks), fine markers.",
    "play": "Draw icons on 3 cubes: Cube 1 (Characters: Dragon, Astronaut, Detective), Cube 2 (Settings: Desert, Castle, Underwater), Cube 3 (Objects: Clock, Wand, Key). Roll and tell an improvised tale!",
    "bonus": "Every family member adds one sentence to the story based on their roll.",
    "amazon": "rorys story cubes"
  },
  {
    "id": "yarn_monsters",
    "title": "Fluffy Wool Pom-Pom Pocket Monsters",
    "category": "Creative & Craft Studio",
    "icon": "🧶",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Skein of yarn, cardboard donut ring, scissors, glue, googly eyes.",
    "play": "Wind yarn repeatedly around cardboard rings, snip the edges, and tie tight in the center to fluff out a lush wool pom-pom. Glue on felt ears and googly eyes!",
    "bonus": "Attach a safety pin or keychain loop to carry your pocket pet on your school bag.",
    "amazon": "pom pom maker kit"
  },
  {
    "id": "tin_foil_sculpture",
    "title": "Olympic Silver Tin-Foil Action Figure Sculpting",
    "category": "Creative & Craft Studio",
    "icon": "🤺",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Roll of kitchen aluminum foil.",
    "play": "Tear off sheets of foil and mold without glue or scissors into dynamic poseable athletes, dragons, medieval knights, or futuristic motorcycles.",
    "bonus": "Host an art gallery opening where family members bid imaginary buttons on the best sculpture.",
    "amazon": "modeling clay non toxic kids"
  },
  {
    "id": "popsicle_catapult",
    "title": "Popsicle Stick & Rubber Band Siege Catapult",
    "category": "Creative & Craft Studio",
    "icon": "🎯",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "8 popsicle sticks, 4 rubber bands, 1 plastic bottle cap, marshmallow or cotton ball.",
    "play": "Stack 6 sticks and bind at both ends with rubber bands. Wedge a lever stick through, strap on a bottle cap basket, and fling soft pom-poms into paper cup targets!",
    "bonus": "Measure launch trajectories: what fulcrum angle sends marshmallows the farthest?",
    "amazon": "jumbo popsicle sticks craft"
  },
  {
    "id": "newspaper_fashion",
    "title": "High-Couture Recycled Newspaper Runway Show",
    "category": "Creative & Craft Studio",
    "icon": "👗",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Sibling or Family",
    "needs": "Old newspapers, tape, scissors.",
    "play": "Design dramatic pleated gowns, warrior chest plates, samurai hats, and superhero capes entirely from folded newspaper. Walk the living room catwalk to dramatic music!",
    "bonus": "Parents play Parisian fashion judges giving commentary with silly accents.",
    "amazon": "costume dress up kids"
  },
  {
    "id": "nature_suncatcher",
    "title": "Contact Paper Fresh Flower & Herb Suncatcher",
    "category": "Creative & Craft Studio",
    "icon": "🌸",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Clear sticky contact paper, colorful flower petals and flat leaves from the garden.",
    "play": "Arrange fresh petals, clover leaves, and grass blades onto sticky contact paper in a kaleidoscope mandala. Seal with a second sheet and stick on a window.",
    "bonus": "Notice how sunlight transforms the green chlorophyll into translucent stained glass.",
    "amazon": "contact paper clear roll"
  },
  {
    "id": "cardboard_guitar",
    "title": "Rockstar Rubber-Band Cardboard Shoebox Guitar",
    "category": "Creative & Craft Studio",
    "icon": "🎸",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Empty tissue box or small shoebox, 4-6 rubber bands of varying thicknesses, cardboard neck tube.",
    "play": "Stretch rubber bands over the open sound hole of the tissue box. Pluck different bands to hear high and low pitch variations based on tension and band thickness!",
    "bonus": "Decorate with flame stickers and stage an acoustic rock concert for the family.",
    "amazon": "rubber bands assortment"
  },
  {
    "id": "paper_quilling",
    "title": "Paper Quilling Spiral Galaxy & Flower Cards",
    "category": "Creative & Craft Studio",
    "icon": "🌀",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Thin strips of colored paper (3-5mm), toothpick or pen, glue.",
    "play": "Roll paper strips tightly around a toothpick, allow to relax into loose coils, and pinch into teardrops, marquis eyes, and crescent moons. Glue into stunning filigree art.",
    "bonus": "Create a 3D monogram of your first initial adorned with paper flower blooms.",
    "amazon": "paper quilling kit for beginners"
  },

  # -------------------------------------------------------------
  # 3. 🔬 STEM & KITCHEN EXPERIMENTS (20 Activities)
  # -------------------------------------------------------------
  {
    "id": "baking_soda_volcano",
    "title": "Foaming Kitchen Vinegar & Baking Soda Volcano",
    "category": "STEM & Kitchen",
    "icon": "🌋",
    "prep": "5 min",
    "mess": "Craft Fun",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Baking dish/tray, small cup, 2 tbsp baking soda, dish soap, red food coloring, 1/2 cup vinegar.",
    "play": "Place the cup in a deep dish. Add baking soda, a squirt of dish soap, and red dye. Pour in vinegar and watch bubbly carbon-dioxide lava foam erupt over the rim!",
    "bonus": "Experiment with vinegar temperature: does warm vinegar make the lava foam faster?",
    "amazon": "volcano science kit for kids"
  },
  {
    "id": "density_rainbow_tower",
    "title": "7-Layer Liquid Density Rainbow Laboratory",
    "category": "STEM & Kitchen",
    "icon": "🧪",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Tall clear glass, honey, dish soap, water (colored blue), vegetable oil, rubbing alcohol.",
    "play": "Slowly pour each liquid down the side of the glass in order of density. Marvel as the liquids float on top of each other in crisp, vibrant colored layers without mixing!",
    "bonus": "Drop a metal nut, a grape, and a piece of sponge to see at which layer each object rests.",
    "amazon": "food coloring liquid set"
  },
  {
    "id": "mug_cake_chemist",
    "title": "3-Minute Microwave Choco Mug Cake Chemistry",
    "category": "STEM & Kitchen",
    "icon": "🧁",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Mug, 3 tbsp flour, 2 tbsp sugar, 1 tbsp cocoa powder, 1/4 tsp baking powder, 3 tbsp milk, 1 tbsp oil.",
    "play": "Whisk dry ingredients in a mug with a fork, stir in milk and oil until glossy. Microwave for 70 seconds and observe baking powder leavening gas in action!",
    "bonus": "Top with a scoop of vanilla ice cream to study thermal melting contrast.",
    "amazon": "kids baking set with utensils"
  },
  {
    "id": "sink_or_float",
    "title": "Buoyancy Mystery: Sink or Float Water Lab",
    "category": "STEM & Kitchen",
    "icon": "🚢",
    "prep": "2 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "Large basin/bowl filled with water, 10 household items (apple, orange with peel vs peeled, coin, paperclip, crayon, Lego brick).",
    "play": "Make a written prediction sheet before testing each item. Test the mystery of the peeled orange: why does an unpeeled orange float while a peeled orange sinks?",
    "bonus": "Fashion a boat out of a 4x4 inch square of aluminum foil: how many coins can it hold before sinking?",
    "amazon": "science lab kit for kids"
  },
  {
    "id": "rainbow_celery",
    "title": "Walking Water & Celery Capillary Action Test",
    "category": "STEM & Kitchen",
    "icon": "🌱",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "2 clear glasses, water, bright food coloring (red/blue), 2 fresh celery stalks with leaves (or white carnations).",
    "play": "Place celery stalks in colored water cups on the kitchen counter. Observe every 2 hours as capillary xylem tubes pull colored water up into the leaves!",
    "bonus": "Split one celery stalk halfway down the middle and place one half in blue and one half in red water!",
    "amazon": "kids microscope with slides"
  },
  {
    "id": "static_balloon_electricity",
    "title": "Static Electricity Bending Water & Dancing Pepper",
    "category": "STEM & Kitchen",
    "icon": "⚡",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "Inflated balloon, wool sweater or dry hair, plate with salt and black pepper, kitchen sink.",
    "play": "Rub balloon vigorously against hair for 15 seconds. Hold near the plate—black pepper flakes magically jump into the air! Hold near a trickle of tap water to bend the stream!",
    "bonus": "Stick the charged balloon against the bedroom wall: how many minutes does static hold it up?",
    "amazon": "snap circuits jr electronics kit"
  },
  {
    "id": "marshmallow_bridge",
    "title": "Toothpick & Marshmallow Civil Engineering Bridge",
    "category": "STEM & Kitchen",
    "icon": "🌉",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "Box of toothpicks, bag of mini marshmallows (or playdough balls / soaked chickpeas).",
    "play": "Engineer 3D geometric trusses, geodesic domes, and suspension bridges. Discover why triangles are the strongest structural shape in architecture.",
    "bonus": "Test bridge strength: span an 8-inch gap between two books and test how many coins it supports before collapsing.",
    "amazon": "stem building toys for kids"
  },
  {
    "id": "magic_milk_swirl",
    "title": "Magic Surface Tension Fireworks in Whole Milk",
    "category": "STEM & Kitchen",
    "icon": "🥛",
    "prep": "3 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Shallow plate with whole milk, 3 colors of food dye, liquid dish soap, cotton swab.",
    "play": "Add drops of food dye to the milk center. Dip a cotton swab in dish soap and touch the middle. Watch colors explode across the surface as soap molecules chase fats!",
    "bonus": "Keep touching different spots to observe continuous molecular swirling currents.",
    "amazon": "pipettes and test tubes kids science"
  },
  {
    "id": "ice_cream_bag",
    "title": "10-Minute Shake-in-a-Bag Vanilla Ice Cream",
    "category": "STEM & Kitchen",
    "icon": "🍨",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "1 small ziplock bag (1/2 cup milk, 1 tbsp sugar, vanilla), 1 gallon ziplock bag (3 cups ice, 1/3 cup rock salt), gloves.",
    "play": "Place the small sealed bag inside the large bag of salted ice. Put on winter gloves and shake vigorously for 7 minutes. Salt depresses ice melting point to freeze cream!",
    "bonus": "Top with chocolate chips and eat your delicious thermodynamics experiment immediately.",
    "amazon": "ice cream maker for kids"
  },
  {
    "id": "homemade_butter",
    "title": "Pioneer Shake-Jar Homemade Cream Butter",
    "category": "STEM & Kitchen",
    "icon": "🧈",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "Clean glass jar with tight lid, 1/2 cup heavy whipping cream, pinch of salt, toast.",
    "play": "Fill the jar half-full with cream. Take turns shaking continuously for 8-10 minutes. First it becomes whipped cream, then suddenly separates into a lump of butter and buttermilk!",
    "bonus": "Pour off buttermilk and spread your fresh hand-churned butter warm on toasted bread.",
    "amazon": "mason jars with lids"
  },
  {
    "id": "diy_compass",
    "title": "Magnetic Needle & Floating Cork Pocket Compass",
    "category": "STEM & Kitchen",
    "icon": "🧭",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Sewing needle, refrigerator bar magnet, cork slice (or bottle cap), shallow bowl of water.",
    "play": "Stroke the needle 50 times in one direction with a magnet to magnetize the steel. Rest the needle across a floating cork slice on water. It will swing and align North-South!",
    "bonus": "Verify against your phone's digital compass app to confirm true magnetic alignment.",
    "amazon": "magnets set for kids physics"
  },
  {
    "id": "dancing_raisins",
    "title": "Bubbly Carbonation Dancing Raisins Submarine",
    "category": "STEM & Kitchen",
    "icon": "🍇",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "Clear tall glass, fresh club soda / sprite (or water + baking soda + vinegar), handful of small raisins.",
    "play": "Drop raisins into fizzy soda. The raisins sink first, but carbon-dioxide bubbles adhere to the wrinkled skin like miniature life jackets, floating them up to the surface!",
    "bonus": "At the surface, bubbles pop and the raisins sink again in a perpetual underwater elevator dance.",
    "amazon": "sparkling water cans"
  },
  {
    "id": "lemon_battery",
    "title": "Citrus Power: The 2-Lemon Electrochemical Clock",
    "category": "STEM & Kitchen",
    "icon": "🍋",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "2 fresh lemons, 2 copper coins/wires, 2 zinc galvanized nails, alligator clip wires, small LED light.",
    "play": "Insert a copper coin and zinc nail into each lemon. Connect in series with alligator wires. The citric acid electrolyte drives electrons between zinc and copper to light the LED!",
    "bonus": "Test whether potatoes or apples produce higher voltage on a household multimeter.",
    "amazon": "lemon clock kit stem science"
  },
  {
    "id": "oobleck_slime",
    "title": "Non-Newtonian Fluid Magic Oobleck Quicksand",
    "category": "STEM & Kitchen",
    "icon": "🥣",
    "prep": "5 min",
    "mess": "Craft Fun",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "2 cups cornstarch, 1 cup water, shallow bowl, food coloring.",
    "play": "Mix cornstarch and water. When you punch the bowl rapidly, it turns rock hard! When you open your palm gently, it melts through your fingers like a liquid!",
    "bonus": "Roll a small handful quickly into a ball—it stays solid until you stop rolling and melts instantly.",
    "amazon": "corn starch bulk"
  },
  {
    "id": "invisible_ink",
    "title": "Lemon Juice Secret Agent Invisible Ink Message",
    "category": "STEM & Kitchen",
    "icon": "🕵️",
    "prep": "3 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Lemon juice, cotton swab or toothpick, white paper, warm incandescent lamp or hair dryer.",
    "play": "Dip cotton swab in lemon juice and write a secret message on paper. Let it dry until completely invisible. Hold paper near a warm light bulb to brown and reveal the secret!",
    "bonus": "Learn why the carbon in citric acid oxidizes faster than paper cellulose under heat.",
    "amazon": "invisible ink pen with uv light"
  },
  {
    "id": "diy_kaleidoscope",
    "title": "Cardboard Tube & Mirror Mylar Kaleidoscope",
    "category": "STEM & Kitchen",
    "icon": "🔮",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "Cardboard tube, reflective foil/mylar strip folded into a triangle, translucent beads, plastic wrap.",
    "play": "Slide the triangular mirror inside the tube. Place colorful translucent beads in a plastic chamber at the end. Turn the tube against window light for endless geometric symmetry!",
    "bonus": "Experiment with polarized light by rotating two sunglasses lenses at the end.",
    "amazon": "diy kaleidoscope kit for kids"
  },
  {
    "id": "solar_oven",
    "title": "Balcony Pizza-Box Solar S'mores Cooker",
    "category": "STEM & Kitchen",
    "icon": "☀️",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo with Parent",
    "needs": "Clean pizza box, aluminum foil, plastic wrap, black paper, biscuits, marshmallows, chocolate.",
    "play": "Line box with foil, place black paper at bottom to absorb heat. Cover top flap with plastic wrap greenhouse barrier. Place in bright midday sun to melt chocolate s'mores!",
    "bonus": "Use a kitchen thermometer to measure the internal greenhouse temperature rise.",
    "amazon": "solar power science kit kids"
  },
  {
    "id": "diy_spectroscope",
    "title": "Recycled CD-ROM Sunlight Rainbow Spectroscope",
    "category": "STEM & Kitchen",
    "icon": "🌈",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "Empty cereal box or paper towel tube, old scratch CD/DVD, tape, razor slit at top.",
    "play": "Cut a viewing angle into the tube and insert the old CD at a 45-degree angle. Look through the eyepiece toward a window to view Fraunhofer rainbow diffraction lines!",
    "bonus": "Compare sunlight spectrum against LED bulbs and candle flames.",
    "amazon": "optical prism physics glass"
  },
  {
    "id": "paper_helicopter",
    "title": "Aerodynamic Paper Rotorcraft Drop Test Lab",
    "category": "STEM & Kitchen",
    "icon": "🚁",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "Paper strips, paperclip, scissors.",
    "play": "Cut a Y-shaped paper rotor, fold blades in opposite directions, and attach a paperclip weight at bottom. Drop from balcony or chair—air resistance spins blades into autorotation!",
    "bonus": "Test blade lengths: do shorter or longer blades achieve more RPM rotations per second?",
    "amazon": "origami paper pack"
  },
  {
    "id": "egg_parachutes",
    "title": "The Raw Egg Astronaut Parachute Drop Test",
    "category": "STEM & Kitchen",
    "icon": "🪂",
    "prep": "10 min",
    "mess": "Craft Fun",
    "energy": "Kitchen & Science",
    "mode": "Solo or Sibling",
    "needs": "Plastic grocery bag or napkin, string, plastic cup, raw egg (or small rock for practice).",
    "play": "Engineer a parachute canopy with strings tied to a passenger capsule cup. Drop from balcony or staircase landing to test if your egg astronaut survives touchdown intact!",
    "bonus": "Add cotton ball shock absorbers and cardboard landing gear legs to minimize impact g-force.",
    "amazon": "parachute toy kids"
  },

  # -------------------------------------------------------------
  # 4. 🧩 QUIET FOCUS & BRAIN QUESTS (20 Activities)
  # -------------------------------------------------------------
  {
    "id": "playing_card_city",
    "title": "Architectural 3-Story Playing Card Skyscraper",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🃏",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "1-2 standard decks of playing cards, flat carpet or table.",
    "play": "Lean pairs of cards into triangular A-frame buttresses. Place horizontal flat roof cards across to support Level 2 and Level 3 stories. Requires deep breath control and focus!",
    "bonus": "Can you engineer a 4-story high-rise without a single card toppling?",
    "amazon": "bicycle playing cards standard"
  },
  {
    "id": "kims_memory_game",
    "title": "Sherlock Holmes Tray-of-15 Kim's Memory Game",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🔍",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Family",
    "needs": "A serving tray, tea towel, 15 assorted household items (key, button, spoon, coin, watch, pencil...).",
    "play": "Uncover the tray for exactly 60 seconds for players to memorize all 15 items. Cover the tray with the towel. Players have 2 minutes to write down all 15 items from memory!",
    "bonus": "Level 2: Sibling secretly removes ONE item while your eyes are closed. Can you identify the missing artifact?",
    "amazon": "memory matching games for kids"
  },
  {
    "id": "diy_jigsaw_puzzle",
    "title": "Hand-Drawn 24-Piece Cardboard Jigsaw Puzzle",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🧩",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "Cereal box cardboard, markers, scissors, envelope.",
    "play": "Draw a vibrant fantasy scene on the cardboard. Flip it over and draw 24 interlocking jigsaw piece shapes with tabs and blanks. Cut out the pieces, mix them up, and solve!",
    "bonus": "Trade puzzles with a family member and race against a 5-minute timer.",
    "amazon": "jigsaw puzzles 100 pieces kids"
  },
  {
    "id": "origami_bookmarks",
    "title": "Corner Monster & Origami Reading Bookmarks",
    "category": "Quiet Focus & Brain Quests",
    "icon": "📚",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Square colored paper (15x15cm), scissors, glue, scrap paper.",
    "play": "Fold a triangular corner pocket bookmark that hugs the top corner of your book page. Glue on sharp white monster teeth, angry eyebrows, or cute bunny ears!",
    "bonus": "Make a set of 5 distinct monsters for your school textbooks.",
    "amazon": "origami paper square double sided"
  },
  {
    "id": "word_chain_shiritori",
    "title": "The Infinite Word-Chain Vocabulary Marathon",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🔤",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Family",
    "needs": "2 or more players.",
    "play": "Player 1 says a word (e.g. 'ELEPHANT'). Player 2 must immediately say a word starting with the last letter (T -> 'TIGER'). Player 3 continues (R -> 'ROCKET'). No repeating words!",
    "bonus": "Themed rounds: Animals only, Countries only, or Foods only!",
    "amazon": "scrabble board game original"
  },
  {
    "id": "matchstick_puzzles",
    "title": "Matchstick Geometric Brain-Teaser Equations",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🥢",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "Box of wooden toothpicks or craft matchsticks.",
    "play": "Lay out math equations or shapes in matchsticks (e.g. Roman numeral 'VI + II = IX'). Move exactly ONE matchstick to correct the equation or turn 5 squares into 4!",
    "bonus": "Invent your own matchstick riddle to stump your parents at dinner.",
    "amazon": "brain teaser puzzles wooden"
  },
  {
    "id": "tangram_master",
    "title": "7-Piece Ancient Chinese Tangram Silhouette Puzzle",
    "category": "Quiet Focus & Brain Quests",
    "icon": "📐",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "1 square of cardboard cut into the traditional 7 tangram pieces (5 triangles, 1 square, 1 parallelogram).",
    "play": "Rearrange all 7 geometric pieces without overlapping to form silhouettes: a running person, a cat, a sailing boat, a house, and a swan.",
    "bonus": "Time yourself to see how quickly you can return all 7 pieces back into the original perfect square.",
    "amazon": "wooden tangram puzzle book"
  },
  {
    "id": "secret_handshake",
    "title": "Invent an Elaborate 10-Step Family Secret Handshake",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🤝",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Parent-Kid",
    "needs": "2 partners.",
    "play": "Choreograph a top-secret 10-step handshake sequence: palm slap, knuckle bump, elbow tap, finger snap, secret spin, hip bump, and freeze pose.",
    "bonus": "Must be performed flawlessly before entering the kitchen for snack time!",
    "amazon": "board games for families"
  },
  {
    "id": "blind_contour_drawing",
    "title": "Funny Blind-Contour Portrait Sketching",
    "category": "Quiet Focus & Brain Quests",
    "icon": "✏️",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Duo",
    "needs": "Paper, pencil.",
    "play": "Sit facing your partner. Look ONLY at their face and draw their portrait without ever looking down at your paper, and without lifting your pencil! Hilarious results guaranteed.",
    "bonus": "Sign your masterpiece and present it in an imaginary Sotheby's art auction.",
    "amazon": "sketch book for drawing"
  },
  {
    "id": "sudoku_detective",
    "title": "Junior 4x4 & 6x6 Sudoku Number Grid Solvers",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🔢",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Paper with drawn grid, pencil, eraser.",
    "play": "Fill a 4x4 or 6x6 grid with numbers 1 to 4 (or 1 to 6) so that every row, column, and sub-block contains each number exactly once without repeats.",
    "bonus": "Replace numbers with symbols (⭐, ☀️, 🌙, ⚡) for a celestial logic challenge.",
    "amazon": "sudoku puzzle books for kids"
  },
  {
    "id": "morse_code_taps",
    "title": "Morse Code Pencil-Tap Telegraph Operator",
    "category": "Quiet Focus & Brain Quests",
    "icon": "📻",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Duo",
    "needs": "Pencil, tabletop, International Morse Code sheet (Dots and Dashes).",
    "play": "Tap short (dot) and long (dash) pencil clicks on the tabletop. Send secret SOS signals or tap out full words for your sibling across the room to decode.",
    "bonus": "Use a flashlight at night from across the garden to blink optical Morse signals.",
    "amazon": "walkie talkies for kids"
  },
  {
    "id": "acrostic_poetry",
    "title": "Family Member Acrostic Name Poetry Book",
    "category": "Quiet Focus & Brain Quests",
    "icon": "✍️",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Paper, colored gel pens.",
    "play": "Write a family member's name vertically down the left margin (e.g. M-O-T-H-E-R). Write a poetic, funny, or heartfelt sentence starting with each letter.",
    "bonus": "Gift the finished illustrated poem as a framed surprise on their desk.",
    "amazon": "calligraphy pen set for beginners"
  },
  {
    "id": "coin_spinning_derby",
    "title": "Tabletop Coin Spinning Velocity Derby",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🪙",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "5 different coins (₹1, ₹2, ₹5, ₹10, ₹20), smooth tabletop, stopwatch.",
    "play": "Spin coins on edge between thumb and index finger. Time how long each coin spins before wobbling and settling flat. Discover how coin thickness and edge ridges affect spin duration!",
    "bonus": "Spin 3 coins simultaneously without allowing them to collide.",
    "amazon": "spinning top metal precision"
  },
  {
    "id": "mindfulness_sensory",
    "title": "The 5-4-3-2-1 Zen Sensory Calm Quest",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🧘",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Quiet room or balcony.",
    "play": "Sit cross-legged. Observe and whisper: 5 things you can see, 4 things you can physically feel, 3 things you can hear, 2 things you can smell, and 1 thing you are grateful for.",
    "bonus": "Instant calming reset after a loud or chaotic day.",
    "amazon": "mindfulness cards for kids"
  },
  {
    "id": "twenty_questions",
    "title": "The Master Mind: 20 Questions Mystery Object",
    "category": "Quiet Focus & Brain Quests",
    "icon": "❓",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Family",
    "needs": "2 or more players.",
    "play": "Leader thinks of a person, place, or thing. Players have up to 20 Yes/No questions to deduce the mystery (e.g. 'Is it alive?', 'Is it bigger than a microwave?').",
    "bonus": "Can you deduce the answer in under 10 questions?",
    "amazon": "20 questions electronic game"
  },
  {
    "id": "rhyme_time_duel",
    "title": "Lightning-Round Rhyme Duel Championship",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🎤",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Duo",
    "needs": "2 players.",
    "play": "Player 1 calls a word (e.g. 'CAT'). Players alternate back and forth providing genuine rhyming words ('BAT', 'HAT', 'FLAT', 'SPLAT', 'MAT') within a 3-second countdown.",
    "bonus": "First player to hesitate or repeat a word yields the round.",
    "amazon": "rhyming card games kids"
  },
  {
    "id": "mini_mandala",
    "title": "Geometric Compass & Protractor Mandala Art",
    "category": "Quiet Focus & Brain Quests",
    "icon": "☸️",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "School geometry compass, pencil, ruler, colored fine-tip pens.",
    "play": "Draw interlocking circles by placing the compass needle on the circumference of your first circle to construct the ancient 'Flower of Life' pattern. Color in symmetric quadrants.",
    "bonus": "Deeply relaxing flow state geometry.",
    "amazon": "geometry compass set school"
  },
  {
    "id": "time_capsule",
    "title": "Secret 1-Year Family Time Capsule Vault",
    "category": "Quiet Focus & Brain Quests",
    "icon": "⏳",
    "prep": "10 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Family",
    "needs": "Sturdy jar or tin, paper, pen, a few small current artifacts.",
    "play": "Write a letter to your future self: current height, best friend, favorite song, current world news, predictions for next year. Seal in a tin with today's date labeled: DO NOT OPEN UNTIL 1 YEAR!",
    "bonus": "Trace your handprint on paper inside to compare hand growth next year.",
    "amazon": "stainless steel time capsule container"
  },
  {
    "id": "card_memory_match",
    "title": "Concentration Card Memory Grid Match",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🎴",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "12 pairs of matching playing cards (24 cards total).",
    "play": "Shuffle and lay cards facedown in a 4x6 grid. Turn over 2 cards per turn trying to find pairs. If they don't match, flip back down. Memorize locations to sweep the board!",
    "bonus": "Solo speed run: can you clear all 12 pairs in under 90 seconds?",
    "amazon": "memory matching card game"
  },
  {
    "id": "finger_puppet_fable",
    "title": "Origami Paper Finger-Puppet Aesop Fable",
    "category": "Quiet Focus & Brain Quests",
    "icon": "🦊",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "Paper cylinders/finger cones, markers.",
    "play": "Roll paper cones to fit your fingers. Draw characters (Tortoise & Hare, Fox & Crow). Stage an improvised retelling of an ancient moral fable from your fingertips.",
    "bonus": "Give each finger puppet a different humorous vocal accent.",
    "amazon": "finger puppets set for kids"
  },

  # -------------------------------------------------------------
  # 5. 🌿 OUTDOOR & BALCONY NATURE SAFARI (18 Activities)
  # -------------------------------------------------------------
  {
    "id": "cloud_mythology",
    "title": "Balcony Sky Cloud-Shape Mythological Safari",
    "category": "Nature & Balcony Safari",
    "icon": "☁️",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "Balcony, terrace, or backyard blanket on a partly cloudy afternoon.",
    "play": "Lie back and observe drifting cumulus clouds. Spot dragons, pirate ships, teapots, and elephants. Sketch the shifting shapes in a cloud notebook.",
    "bonus": "Learn the difference between puffy Cumulus, wispy Cirrus, and dark Stratus rain clouds.",
    "amazon": "kids binoculars compact"
  },
  {
    "id": "birdwatching_tally",
    "title": "Morning Balcony Bird Watch & Song Tally",
    "category": "Nature & Balcony Safari",
    "icon": "🐦",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Window, balcony, notebook, pencil (optional binoculars).",
    "play": "Sit quietly for 15 minutes at dawn or late afternoon. Tally species: Mynahs, Pigeons, Crows, Sunbirds, Sparrows, Parakeets. Note their flight patterns and songs.",
    "bonus": "Place a shallow clay bowl of fresh water on the parapet to create a bird bath oasis.",
    "amazon": "birds of india field guide book"
  },
  {
    "id": "balcony_puddle_splash",
    "title": "Balcony Paper Boat Regatta & Monsoon Waves",
    "category": "Nature & Balcony Safari",
    "icon": "⛵",
    "prep": "3 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Paper boats folded from scrap paper, wide water tub or rainy balcony puddle.",
    "play": "Fold traditional pointed paper boats. Blow on the water or use a hand fan to race them across the water basin without capsizing.",
    "bonus": "Load tiny pebbles inside as 'cargo' to test maximum freight capacity before sinking.",
    "amazon": "origami paper waterproof"
  },
  {
    "id": "chalk_obstacle_course",
    "title": "Terrace / Driveway Sidewalk Chalk Ninja Course",
    "category": "Nature & Balcony Safari",
    "icon": "🖍️",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Sidewalk chalk, terrace, patio, or driveway.",
    "play": "Draw an interactive chalk course: 'Spin 3 times', 'Tip-toe on the squiggly snake', 'Frog jump 5 circles', 'High-speed sprint', and 'Moon landing hop'.",
    "bonus": "Time each other with a stopwatch to set the neighborhood track record.",
    "amazon": "sidewalk chalk jumbo bucket"
  },
  {
    "id": "micro_nature_safari",
    "title": "1-Square-Meter Microscopic Garden Safari",
    "category": "Nature & Balcony Safari",
    "icon": "🐜",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo or Sibling",
    "needs": "1 meter piece of string, magnifying glass, notebook.",
    "play": "Lay the string in a circle on the garden lawn or flowerpot bed. Examine every square inch inside: count ants, inspect moss texture, watch pillbugs roll up into armor balls.",
    "bonus": "Draw an explorer's map of your micro-jungle.",
    "amazon": "magnifying glass for kids"
  },
  {
    "id": "balcony_sundial",
    "title": "Ancient Egyptian Balcony Shadow Sundial",
    "category": "Nature & Balcony Safari",
    "icon": "☀️",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "Paper plate, straight stick or pencil poked in center, sunny balcony or terrace.",
    "play": "Place the plate in sunlight. Every hour on the hour (9 AM, 10 AM, 11 AM...), trace the cast shadow with a pen and write the hour. You now have a working solar clock!",
    "bonus": "Check your sundial the next day: how accurate is solar time vs your wrist watch?",
    "amazon": "educational sundial compass"
  },
  {
    "id": "aerodynamic_airplane_olympics",
    "title": "Balcony Aerodynamic Paper Glider Olympics",
    "category": "Nature & Balcony Safari",
    "icon": "✈️",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Solo or Sibling",
    "needs": "Paper sheets, target hula hoop or laundry basket.",
    "play": "Fold 3 distinct aircraft models: The Dart (high speed), The Glider (wide wingspan for long loft), and The Stunt Plane (flaps bent for loop-de-loops). Test distance and hangtime!",
    "bonus": "Bend wing ailerons upward or downward to test banking turns.",
    "amazon": "paper airplane book with printed paper"
  },
  {
    "id": "flowerpot_seedling",
    "title": "Kitchen Fenugreek & Mustard Seedling Sprout Lab",
    "category": "Nature & Balcony Safari",
    "icon": "🌱",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "Small cup or pot with soil (or wet cotton in a saucer), mustard or methi (fenugreek) seeds from kitchen.",
    "play": "Sprinkle seeds over moist soil, cover with a light sprinkle of dirt, and water gently. Place on a warm windowsill. Seeds sprout emerald micro-greens in just 48 hours!",
    "bonus": "Measure sprout height daily with a ruler and plot your plant's growth curve.",
    "amazon": "kids gardening tools set"
  },
  {
    "id": "wind_chime_sculpture",
    "title": "Upcycled Shell & Metal Spoon Balcony Wind Chime",
    "category": "Nature & Balcony Safari",
    "icon": "🎐",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo with Parent",
    "needs": "Stick from garden, old keys or metal spoons, sea shells, string.",
    "play": "Tie spoons, keys, and shells with strings hanging from a horizontal garden branch. Hang on the balcony grill where the evening breeze plays melodic metal chimes.",
    "bonus": "Paint the suspension stick in bright rainbow stripes.",
    "amazon": "diy wind chime kit kids"
  },
  {
    "id": "weather_station_log",
    "title": "Junior Meteorologist Weekly Weather Journal",
    "category": "Nature & Balcony Safari",
    "icon": "⛅",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Notebook, ruler, thermometer or outdoor look.",
    "play": "Log daily morning conditions: temperature, cloud cover percentage (0-100%), wind speed (gentle breeze vs gusty), and humidity. Predict tomorrow's rain chances!",
    "bonus": "Build a simple rain gauge using a cut plastic water bottle with inch markings.",
    "amazon": "weather station for kids"
  },
  {
    "id": "bug_hotel",
    "title": "Balcony Solitary Bee & Ladybug Wood Hotel",
    "category": "Nature & Balcony Safari",
    "icon": "🏨",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Solo or Sibling",
    "needs": "Tin can or small wooden box, hollow bamboo straws, pinecones, twigs, dried leaves.",
    "play": "Bundle hollow sticks and pinecones tightly inside the can. Hang horizontally in a sheltered balcony garden corner to provide a safe winter haven for beneficial pollinators!",
    "bonus": "Observe which insects check into the hotel rooms over the coming weeks.",
    "amazon": "bug hotel for garden"
  },
  {
    "id": "scent_safari",
    "title": "Garden Herb & Spice Scent Guessing Blindfold",
    "category": "Nature & Balcony Safari",
    "icon": "👃",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Duo",
    "needs": "Blindfold, crushed leaves and herbs (Mint, Tulsi, Rosemary, Curry Leaf, Lemon peel, Cinnamon).",
    "play": "Blindfold your partner and hold different crushed leaves under their nose. Can they identify the plant purely through olfactory memory?",
    "bonus": "Score 10 points for every correctly identified culinary herb.",
    "amazon": "herb garden kit indoor"
  },
  {
    "id": "pressed_flower_stationery",
    "title": "Heavy-Book Pressed Flower Bookmark Studio",
    "category": "Nature & Balcony Safari",
    "icon": "🌺",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Fresh fallen flowers, tissue paper, heavy encyclopedias or dictionary.",
    "play": "Place flat blossoms between sheets of tissue paper inside a thick heavy book. Place 2 more heavy books on top. After 5 days, reveal delicate, paper-thin pressed botanical treasures!",
    "bonus": "Glue pressed flowers onto cardstock to make personalized greeting cards.",
    "amazon": "wooden flower press kit"
  },
  {
    "id": "outdoor_tic_tac_toe",
    "title": "Rustic Twig & Painted Pebble Tic-Tac-Toe",
    "category": "Nature & Balcony Safari",
    "icon": "❌",
    "prep": "3 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Duo",
    "needs": "4 straight twigs for grid, 5 smooth pebbles painted with 'X' and 5 with 'O'.",
    "play": "Arrange twigs in a 3x3 grid on the balcony floor. Play tactical tic-tac-toe matches using organic rock tokens.",
    "bonus": "Best of 7 series crowned as the Grandmaster of the Garden.",
    "amazon": "travel board games kids"
  },
  {
    "id": "shadow_silhouette_tracing",
    "title": "Sunlight Toy Animal Silhouette Tracing Art",
    "category": "Nature & Balcony Safari",
    "icon": "🦒",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Solo Play",
    "needs": "Toy animals/dinosaurs, white paper, sunny balcony floor, pencil.",
    "play": "Line up toy figurines along the edge of the paper so afternoon sun casts sharp dramatic shadows across the sheet. Carefully trace the outline silhouettes with a pencil!",
    "bonus": "Color inside the traced silhouettes with watercolor sunset gradients.",
    "amazon": "animal figures toy set"
  },
  {
    "id": "star_constellation_viewer",
    "title": "Night Sky Cardboard Constellation Projector",
    "category": "Nature & Balcony Safari",
    "icon": "✨",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Quiet Focus",
    "mode": "Solo with Parent",
    "needs": "Toilet paper tube, circle of black paper, pin/needle, flashlight.",
    "play": "Poke pinhole patterns of famous constellations (Ursa Major, Orion's Belt, Cassiopeia) into black paper and tape to the tube end. Shine flashlight through in a dark room to project stars!",
    "bonus": "Step outside onto the terrace to locate the real Orion's Belt in the night sky.",
    "amazon": "astronomy star chart for kids"
  },
  {
    "id": "pinecone_weather_predictor",
    "title": "Nature's Hygrometer: The Pinecone Humidity Gauge",
    "category": "Nature & Balcony Safari",
    "icon": "🌲",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Solo Play",
    "needs": "Dry pinecone on the balcony sill.",
    "play": "Observe the pinecone daily: in dry sunny air, scales open wide to release seeds; when rain or high humidity approaches, scales close tight to protect seeds from moisture!",
    "bonus": "Dip the pinecone in a bowl of water to watch it snap shut right before your eyes within 30 minutes.",
    "amazon": "natural pine cones craft"
  },
  {
    "id": "nature_soundscape_map",
    "title": "360-Degree Blindfold Nature Soundscape Map",
    "category": "Nature & Balcony Safari",
    "icon": "🎧",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Solo Play",
    "needs": "Paper with an 'X' drawn in center (representing you), colored pencils.",
    "play": "Sit silently on the balcony for 10 minutes with eyes closed. Whenever you hear a sound, map its direction and distance relative to 'X' (e.g. distant dog barking at 2 o'clock, rustling leaves at 7 o'clock).",
    "bonus": "Develops deep acoustic mindfulness and situational awareness.",
    "amazon": "nature journal for kids"
  },

  # -------------------------------------------------------------
  # 6. 🤝 FAMILY & SIBLING TEAM CHALLENGES (20 Activities)
  # -------------------------------------------------------------
  {
    "id": "blindfold_obstacle_guide",
    "title": "Trust Walk: Blindfolded Navigator Obstacle Course",
    "category": "Family & Sibling Challenges",
    "icon": "🦯",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Duo",
    "needs": "Blindfold (scarf), living room floor with a few soft pillow obstacles.",
    "play": "Partner A is blindfolded. Partner B can ONLY use verbal directional cues ('Take 2 baby steps forward, turn 45 degrees left, step high over the blue cushion') to guide them safely across the room!",
    "bonus": "Switch roles and try doing it in reverse without speaking, using only tap signals on shoulders!",
    "amazon": "sleep mask blindfold soft"
  },
  {
    "id": "two_minute_charades",
    "title": "Family Charades & Movie/Action Mime Challenge",
    "category": "Family & Sibling Challenges",
    "icon": "🎭",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "Paper slips with funny prompts, timer.",
    "play": "Act out prompts ('Eating spaghetti with chopsticks', 'Washing a grumpy cat', 'Superhero landing') without speaking or making vocal sounds. First team to guess within 60 seconds scores 100 points!",
    "bonus": "Category twist: Famous movie titles or household teacher impressions!",
    "amazon": "charades for kids game"
  },
  {
    "id": "kid_restaurant",
    "title": "The Kid-Run 5-Star Gourmet Evening Cafe",
    "category": "Family & Sibling Challenges",
    "icon": "🍽️",
    "prep": "10 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Family Challenge",
    "needs": "Handwritten menu card, paper napkins, light snacks/beverages.",
    "play": "Kids take over the dining room: seat parents at a decorated candlelit table, present an illustrated handwritten menu with funny pricing (e.g. 'Apple slices: 3 hugs and 1 joke'), and serve snacks as courteous waiters!",
    "bonus": "Parents leave an enthusiastic tip in the child's piggy bank.",
    "amazon": "pretend play restaurant set"
  },
  {
    "id": "family_trivia_night",
    "title": "The Great 'How Well Do You Know Mom & Dad?' Quiz",
    "category": "Family & Sibling Challenges",
    "icon": "🎙️",
    "prep": "5 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Family Challenge",
    "needs": "Notepad, pens.",
    "play": "Kids act as quizmasters asking parents questions: 'What was Dad's first car?', 'What is Mom's favorite comfort food?', 'What was our family's funniest vacation mishap?'.",
    "bonus": "Flip the tables: parents quiz kids on their secret dreams and best friends.",
    "amazon": "family quiz game cards"
  },
  {
    "id": "whisper_telephone",
    "title": "The Hilarious Broken Telephone Whispering Chain",
    "category": "Family & Sibling Challenges",
    "icon": "📞",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Family Challenge",
    "needs": "3 or more players seated in a circle.",
    "play": "Player 1 whispers a complicated, funny tongue-twister sentence once into Player 2's ear. It gets whispered down the chain. The last person announces what they heard aloud!",
    "bonus": "Laugh uncontrollably at how 'The purple penguin painted pink pancakes' turned into 'My brother's shoes stink'.",
    "amazon": "classic party games"
  },
  {
    "id": "blind_taste_test",
    "title": "MasterChef Blindfold Flavor & Crunch Mystery Test",
    "category": "Family & Sibling Challenges",
    "icon": "🍓",
    "prep": "5 min",
    "mess": "Low Mess",
    "energy": "Kitchen & Science",
    "mode": "Family Challenge",
    "needs": "Blindfold, small samples on spoons: chocolate chip, slice of apple, banana, dab of peanut butter, cheese cube, grape, pickle.",
    "play": "Blindfolded player takes a bite and must guess the food within 5 seconds using only taste and texture receptors.",
    "bonus": "Score an extra 50 points if you can name the exact seasoning or spice!",
    "amazon": "kids chef apron and hat"
  },
  {
    "id": "family_talent_show",
    "title": "Living Room Saturday Evening Got Talent Extravaganza",
    "category": "Family & Sibling Challenges",
    "icon": "🌟",
    "prep": "10 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "Stage space in living room, sofa seating for judges, spoon microphone.",
    "play": "Every family member prepares a 2-minute act: magic trick, singing, standup comedy jokes, gymnastics routine, or poetry recitation. Award golden buzzer paper stars!",
    "bonus": "Record with a phone for precious family memory archives.",
    "amazon": "kids magic set starter"
  },
  {
    "id": "cup_tower_showdown",
    "title": "Speed-Stacking 36-Plastic Cup Pyramid Showdown",
    "category": "Family & Sibling Challenges",
    "icon": "🥤",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Duo",
    "needs": "36 paper or plastic cups, flat table, timer.",
    "play": "Race against the clock to build a 6-tier pyramid (6-5-4-3-2-1), then collapse it down into a single stack with both hands without knocking cups onto the floor.",
    "bonus": "Head-to-head duel: two players build side-by-side pyramids simultaneously!",
    "amazon": "speed stacking cups game"
  },
  {
    "id": "two_truths_one_lie",
    "title": "Two Truths & A Lie: The Master Deceiver",
    "category": "Family & Sibling Challenges",
    "icon": "🤥",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Family Challenge",
    "needs": "3 or more players.",
    "play": "Each player states 3 statements about their past adventures, hidden talents, or preferences (2 true, 1 completely fabricated). The family interrogates and votes on the lie!",
    "bonus": "Discover surprising childhood stories parents never told before.",
    "amazon": "family conversation cards"
  },
  {
    "id": "cardboard_car_rally",
    "title": "Precision Floor Target Hot Wheels & Toy Car Rally",
    "category": "Family & Sibling Challenges",
    "icon": "🏎️",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Duo",
    "needs": "Diecast toy cars, taped parking bays with 10, 20, 50, 100 point zones.",
    "play": "Slide toy cars from 10 feet away trying to park precisely inside the 100-point parking bay without overshooting into the penalty ditch.",
    "bonus": "3 rounds with 3 cars each to determine the Grand Prix Champion.",
    "amazon": "hot wheels cars pack"
  },
  {
    "id": "pillow_fight_balancing",
    "title": "Gentle Balance-Beam Bed Pillow Duel",
    "category": "Family & Sibling Challenges",
    "icon": "🥊",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling Duo",
    "needs": "Carpeted floor, soft pillows, line of tape or low bench.",
    "play": "Both players stand with both feet on a taped line on the carpet. Use soft pillows with gentle swings to throw your opponent off-balance while keeping your feet planted!",
    "bonus": "First to step off the tape concedes the round.",
    "amazon": "soft bed pillows standard"
  },
  {
    "id": "family_portrait_relay",
    "title": "Pass-the-Canvas 1-Minute Family Portrait Relay",
    "category": "Family & Sibling Challenges",
    "icon": "🎨",
    "prep": "2 min",
    "mess": "Low Mess",
    "energy": "Creative Arts",
    "mode": "Family Challenge",
    "needs": "1 large sheet of paper, colored markers, 1-minute timer.",
    "play": "Player 1 draws for 60 seconds (outline of head/body), passes the sheet to Player 2 (adds funny hair and glasses), passes to Player 3 (adds wacky background and pet).",
    "bonus": "Reveal the hilarious collaborative masterwork to the entire family.",
    "amazon": "drawing pad large sketch"
  },
  {
    "id": "pictionary_whiteboard",
    "title": "Kitchen Whiteboard Lightning Pictionary Duel",
    "category": "Family & Sibling Challenges",
    "icon": "🖍️",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "Dry-erase whiteboard or scrap paper, markers, 60-second timer.",
    "play": "Artist has 60 seconds to draw a secret prompt ('Riding a camel in the snow', 'Eating an ice cream that's melting', 'A superhero with broken glasses') without letters or numbers!",
    "bonus": "Team with the most correct guesses in 5 rounds wins the trophy.",
    "amazon": "dry erase whiteboard small"
  },
  {
    "id": "indoor_bocce",
    "title": "Living Room Soft Carpet Bocce Ball",
    "category": "Family & Sibling Challenges",
    "icon": "⚪",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Sibling or Duo",
    "needs": "1 small target ball (e.g. golf ball or white sock), 4 colored balls (tennis balls or rolled socks).",
    "play": "Toss the small white target ball onto the living room carpet. Players take turns rolling their colored balls to land as close as possible to the target.",
    "bonus": "Use tape measure to resolve nail-biting millimeter tie-breakers!",
    "amazon": "indoor bocce ball set soft"
  },
  {
    "id": "paper_bridge_coin_test",
    "title": "Single Sheet of A4 Paper Heavy Coin Bridge Challenge",
    "category": "Family & Sibling Challenges",
    "icon": "🌉",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "Kitchen & Science",
    "mode": "Sibling or Duo",
    "needs": "1 sheet of paper, 2 drinking glasses, 30 heavy coins.",
    "play": "Place glasses 6 inches apart. How can you fold 1 sheet of paper so it supports 30 coins across the gap? (Hint: Accordion fan-folding creates immense structural rigidity!).",
    "bonus": "Test different fold widths to optimize weight-to-span ratio.",
    "amazon": "origami paper pack"
  },
  {
    "id": "spoon_egg_relay",
    "title": "Kitchen Spoon & Lemon Obstacle Relay Race",
    "category": "Family & Sibling Challenges",
    "icon": "🥄",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Sibling or Family",
    "needs": "Tablespoons, lemons or hard-boiled eggs (or plastic practice eggs).",
    "play": "Hold spoon handle firmly in mouth, balance a lemon in the spoon bowl, and navigate around living room chairs and coffee tables without dropping it!",
    "bonus": "If the lemon falls, return to the start line and begin again.",
    "amazon": "egg and spoon race game"
  },
  {
    "id": "silent_actor_mime",
    "title": "Silent Movie: Household Daily Routine Pantomime",
    "category": "Family & Sibling Challenges",
    "icon": "🎬",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Creative Arts",
    "mode": "Family Challenge",
    "needs": "Living room stage.",
    "play": "Actors must perform an entire 3-minute mini melodrama without uttering a single sound. Use over-exaggerated facial expressions and silent film title cards written on paper!",
    "bonus": "Play upbeat silent-movie piano music in the background.",
    "amazon": "classic family games"
  },
  {
    "id": "tongue_twister_championship",
    "title": "Speed Tongue-Twister Household World Cup",
    "category": "Family & Sibling Challenges",
    "icon": "👅",
    "prep": "0 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "List of classic Indian and international tongue-twisters.",
    "play": "Repeat 5 times as fast as possible without stumbling: 'Kacha papita, pakka papita', 'Red lorry, yellow lorry', 'She sells seashells by the seashore'.",
    "bonus": "Time the fastest clean recitation with a digital stopwatch.",
    "amazon": "tongue twister books for kids"
  },
  {
    "id": "balloon_keep_up_coop",
    "title": "Multi-Balloon 3-Airborne Cooperative Challenge",
    "category": "Family & Sibling Challenges",
    "icon": "🎈",
    "prep": "2 min",
    "mess": "Zero Mess",
    "energy": "High Energy",
    "mode": "Family Challenge",
    "needs": "3 inflated balloons, open living room space.",
    "play": "Toss 3 balloons in the air simultaneously. The entire family must work as a unified team to keep all 3 balloons off the floor for a full 60 seconds!",
    "bonus": "Every 15 seconds, add a 4th balloon into the aerial storm!",
    "amazon": "biodegradable balloons pack"
  },
  {
    "id": "family_gratitude_circle",
    "title": "The Golden Candle Family Gratitude & Highs/Lows Circle",
    "category": "Family & Sibling Challenges",
    "icon": "🕯️",
    "prep": "1 min",
    "mess": "Zero Mess",
    "energy": "Quiet Focus",
    "mode": "Family Challenge",
    "needs": "Sofa seating or carpet circle, optional small candle or battery tea light.",
    "play": "Gather together before dinner or bedtime. Pass the light around: each person shares their 'Rose' (favorite highlight of the day), 'Thorn' (something tricky), and 'Bud' (something they look forward to tomorrow).",
    "bonus": "Deepens family bonding, emotional trust, and empathy.",
    "amazon": "gratitude journal for kids"
  }
]

print("Total activities compiled:", len(ACTIVITIES))
with open('scripts/activities_data.json', 'w', encoding='utf-8') as f:
    json.dump(ACTIVITIES, f, indent=2, ensure_ascii=False)
print("Saved scripts/activities_data.json successfully.")
